SSチームの計算リソースの紹介を追加
HPCSLab/web pull request #137
Opened 2024-05-13 08:29 UTC by namachan10777

- 輪講情報の追加
- 研究室にどのくらい人が居るかを記載
- SSチームの計算リソースと、その運用について記載

してみました。

2024-05-13 09:25 UTC, otatebe commented
200 Gbpsではなく400 Gbpsです

2024-05-14 03:05 UTC, namachan10777 commented
@otatebe ありがとうございます。修正しました

2024-05-22 08:04 UTC, shuuji3 requested changes
リンクの追加や誤字の修正などです。

2024-06-18 05:48 UTC, shuuji3 approved these changes
修正ありがとうございます🙏🏻

2024-06-21 06:41 UTC, merged