Show alumnus in the sorted order (year, month, name)
HPCSLab/web pull request #87
Opened 2024-04-19 07:04 UTC by k5342

Alumni ページの名前一覧を日付順にソートして表示するようにしてみました．日付が一致する場合は名前の辞書順になります

2024-04-19 07:14 UTC, k5342 commented on src/pages/members/alumni.astro
> +        })}
使う場所があまりなさそうなのでベタ書きになってます．見栄えを気にして関数に押し込んでも良いと思っているのですがスコープをどこに置くべきかで迷ったのでそのままです．強い思想はないのでもし適切な場所があれば教えて下さい

2024-04-19 12:09 UTC, namachan10777 reviewed
これAstroは静的ビルドで実行時間やメモリフットプリントをあまり気にする必要がないことから、printfパターンではあるものの一旦文字列にして`Data.parse`とかのほうがわかりやすい気もします。

2024-04-21 04:32 UTC, namachan10777 commented
比較関数なの忘れて全順序集合へのマッピング考えちゃってました……

2024-04-21 04:35 UTC, namachan10777 requested changes
やりたいことの割に比較関数がちょっと読みにくい気がしています。今回の場合は実行時間をさほど気にする必要はないので、日付比較を`Data.parse(`${a.year}-${a.month}-1`)`みたいにすると読みやすいかなと思います。

他にこの関数を使う場所は今のところ無いですし、そこまで複雑な実装でも無いのでベタ書きなのはそのままで良いと思います

2024-04-22 13:40 UTC, k5342 commented
コンストラクタがある `new Date(year, month-1)` 形式にしてみました。これだとどうでしょう。Date.parse は好みが分かれそうだったので・・

2024-04-23 04:28 UTC, namachan10777 approved these changes
ありがとうございます！

2024-04-23 04:28 UTC, merged