devContainer: Expose port :4321 for local development
HPCSLab/web pull request #88
Opened 2024-04-19 07:11 UTC by k5342

Port :4321 を expose してホスト側のブラウザからアクセスできるようにします

2024-04-21 04:30 UTC, namachan10777 requested changes
`--host 0.0.0.0`は削ってほしいです

2024-04-22 13:31 UTC, k5342 commented
WSL2 のワークアラウンドでサブコマンド追加させてほしいです。不格好ですけど代案見つかるまでこれで凌がせてもらいたい・・

2024-04-23 04:26 UTC, namachan10777 commented
ワークアラウンドと分かる形のコマンドなら :ok: です

2024-04-23 04:27 UTC, namachan10777 approved these changes

2024-04-23 04:27 UTC, merged