update ss team page
HPCSLab/web pull request #95
Opened 2024-04-22 05:06 UTC by otatebe

SSチームのページを取り急ぎ更新しました。
Youtube の画面を 80% くらいにしたいのですができますか？
あと link はどのように張ればいいでしょう。
合宿の写真とかも差しさわりにない範囲で張れたらと思っています。

2024-04-22 05:56 UTC, otatebe commented
linter に怒られていますけど、修正はどのようにすればいいでしょう

2024-04-22 12:30 UTC, namachan10777 requested changes
YouTubeの幅調整はAstroのコンポーネントを触る必要があるので、一旦はこのままマージしてあとで私がやります。

リンクの方はMarkdownなので `[リンクテキスト](URL)`の形で書けばリンクになります。

画像は`![代替テキスト](画像のパス)`で挿入できます。この場合ですと、`src/content/team/ss/gasshuku.jpg`のようなパスで画像を配置して、`![2024年合宿の集合写真、大洗](./ss/gasshuku.jpg)`のようにするのが良いかと思います。

写真に関しては先生のお手元にないようでしたら、学生の方であとから挿入するのでも打丈夫です。

Linterについてはターミナルで`pnpm run fix`とすれば自動でフォーマットされるので、それをコミットすればチェックが通るはずです。

2024-04-23 04:23 UTC, namachan10777 commented
あ、そっちですか。多分それはCSSの問題なので修正します

2024-04-23 04:25 UTC, namachan10777 approved these changes
リンクのスタイル、Youtubeの幅、合宿の写真はこちらで巻き取ります。更新ありがとうございます。

2024-04-23 04:26 UTC, merged